apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      
    route:
      receiver: 'default-receiver'
      group_by: ['alertname', 'cluster', 'service', 'component']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      
      routes:
      - match:
          severity: critical
        receiver: 'critical-email-receiver'
        group_wait: 0s
        repeat_interval: 1h
        
      - match:
          component: k3s
        receiver: 'k3s-receiver'
        group_by: ['alertname', 'service']
        
      - match:
          component: gpu
        receiver: 'gpu-receiver'
        group_by: ['alertname', 'gpu']
        
      - match:
          component: monitoring-stack
        receiver: 'monitoring-email-receiver'
        group_by: ['alertname', 'service']
        
      - match:
          component: claude-code
        receiver: 'claude-receiver'
        group_by: ['alertname']
        repeat_interval: 24h
        
      - match_re:
          alertname: '.*Power.*|.*Thermal.*|.*Temperature.*|.*Battery.*'
        receiver: 'power-receiver'
        group_wait: 30s
        
      # High/Critical Anomaly Scores -> Email
      - match_re:
          alertname: '.*Anomaly.*'
        receiver: 'anomaly-email-receiver'
        group_wait: 30s
        repeat_interval: 2h
        
    receivers:
    - name: 'default-receiver'
      webhook_configs:
      - url: 'http://webhook-logger:8080/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    # Email bridge receivers for important alerts
    - name: 'critical-email-receiver'
      webhook_configs:
      - url: 'http://email-bridge:8081/'
        send_resolved: true
        title: 'CRITICAL Alert'
      - url: 'http://webhook-logger:8080/critical'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    - name: 'monitoring-email-receiver'
      webhook_configs:
      - url: 'http://email-bridge:8081/'
        send_resolved: true
        title: 'Monitoring Alert'
      - url: 'http://webhook-logger:8080/monitoring'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    - name: 'anomaly-email-receiver'
      webhook_configs:
      - url: 'http://email-bridge:8081/'
        send_resolved: true
        title: 'Anomaly Alert'
      - url: 'http://webhook-logger:8080/anomaly'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    - name: 'k3s-receiver'
      webhook_configs:
      - url: 'http://webhook-logger:8080/k3s'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    - name: 'gpu-receiver'
      webhook_configs:
      - url: 'http://webhook-logger:8080/gpu'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    - name: 'claude-receiver'
      webhook_configs:
      - url: 'http://webhook-logger:8080/claude'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    - name: 'power-receiver'
      webhook_configs:
      - url: 'http://webhook-logger:8080/power'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'odin'
            password: 'monitoring'
            
    inhibit_rules:
    - source_match:
        alertname: 'K3sAPIServerDown'
      target_match_re:
        component: 'k3s'
      equal: ['cluster']
      
    - source_match:
        alertname: 'PrometheusDown'
      target_match:
        alertname: 'PrometheusTargetDown'
      equal: ['instance']
      
    - source_match:
        alertname: 'NodeNotReady'
      target_match_re:
        alertname: 'Pod.*'
      equal: ['node']
      
    - source_match:
        alertname: 'MonitoringStackCritical'
      target_match:
        component: 'monitoring-stack'
        severity: 'warning'