loki:
  auth_enabled: false
  persistence:
    enabled: true
    storageClassName: local-storage-2tb
    size: 50Gi
    existingClaim: loki-pvc
  config:
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
  service:
    type: NodePort
    nodePort: 31495

promtail:
  enabled: true
  config:
    serverPort: 3101
    clients:
      - url: http://loki:3100/loki/api/v1/push