apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-logo
  namespace: monitoring
  labels:
    grafana_logo: odin
data:
  logo.svg: |
    <svg xmlns="http://www.w3.org/2000/svg" width="720" height="360" viewBox="0 0 720 360">
      <defs>
        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#00ff88;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#0099ff;stop-opacity:1" />
        </linearGradient>
        <filter id="glow">
          <feGaussianBlur stdDeviation="4" result="coloredBlur"/>
          <feMerge>
            <feMergeNode in="coloredBlur"/>
            <feMergeNode in="SourceGraphic"/>
          </feMerge>
        </filter>
      </defs>
      
      <!-- ODIN text with gradient - doubled size -->
      <text x="360" y="150" font-family="Arial, sans-serif" font-size="120" font-weight="bold" 
            text-anchor="middle" fill="url(#grad1)" filter="url(#glow)">ODIN</text>
      
      <!-- Subtitle - doubled size -->
      <text x="360" y="240" font-family="Arial, sans-serif" font-size="48" 
            text-anchor="middle" fill="#999">Omnipresent Diagnostics</text>
      <text x="360" y="300" font-family="Arial, sans-serif" font-size="48" 
            text-anchor="middle" fill="#999">Intelligence Network</text>
      
      <!-- Decorative elements - doubled size -->
      <circle cx="90" cy="90" r="18" fill="#00ff88" opacity="0.8"/>
      <circle cx="630" cy="90" r="18" fill="#0099ff" opacity="0.8"/>
      <circle cx="90" cy="270" r="12" fill="#00ff88" opacity="0.6"/>
      <circle cx="630" cy="270" r="12" fill="#0099ff" opacity="0.6"/>
      
      <!-- Connection lines - doubled size -->
      <line x1="108" y1="90" x2="612" y2="90" stroke="#333" stroke-width="6" opacity="0.5"/>
      <line x1="102" y1="270" x2="618" y2="270" stroke="#333" stroke-width="6" opacity="0.5"/>
      
      <!-- Additional network effect -->
      <circle cx="360" cy="90" r="6" fill="#00ccff" opacity="0.6"/>
      <circle cx="360" cy="270" r="6" fill="#00ccff" opacity="0.6"/>
    </svg>