apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider-anomaly
  namespace: monitoring
data:
  anomaly-provider.yaml: |
    apiVersion: 1
    providers:
    - name: 'anomaly'
      orgId: 1
      folder: 'ML Anomaly Detection'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards-anomaly