apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-custom-config
  namespace: monitoring
data:
  custom.ini: |
    [feature_toggles]
    provisioning = true
    kubernetesClientDashboardsFolders = true
    kubernetesDashboards = true
    grafanaAPIServerEnsureKubectlAccess = true
    
    [auth.github]
    enabled = true
    allow_sign_up = true
    client_id = ${GF_AUTH_GITHUB_CLIENT_ID}
    client_secret = ${GF_AUTH_GITHUB_CLIENT_SECRET}
    scopes = user:email,read:org
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    api_url = https://api.github.com/user
    allowed_organizations = 
    team_ids = 
    
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/system-overview.json