apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = odin.local
    root_url = http://odin.local:31494/

    [branding]
    app_title = ODIN - Omnipresent Diagnostics and Intelligence Network
    app_subtitle = System Monitoring Dashboard
    welcome_banner_title = Welcome to ODIN
    welcome_banner_text = Omnipresent Diagnostics and Intelligence Network

    [theme]
    default_theme = dark

    [users]
    default_theme = dark

    [ui]
    app_title = ODIN Monitoring
    
    [auth.anonymous]
    enabled = false

    [security]
    admin_user = admin
    admin_password = admin
    cookie_secure = false
    
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/system-overview.json

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-logo
  namespace: monitoring
  labels:
    grafana_logo: "odin"
data:
  # Simple ASCII-based ODIN logo for login page
  logo.svg: |
    <svg xmlns="http://www.w3.org/2000/svg" width="120" height="60" viewBox="0 0 120 60">
      <defs>
        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#00ff88;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#0099ff;stop-opacity:1" />
        </linearGradient>
      </defs>
      
      <!-- ODIN text with gradient -->
      <text x="60" y="25" font-family="Arial, sans-serif" font-size="20" font-weight="bold" 
            text-anchor="middle" fill="url(#grad1)">ODIN</text>
      
      <!-- Subtitle -->
      <text x="60" y="40" font-family="Arial, sans-serif" font-size="8" 
            text-anchor="middle" fill="#999">Omnipresent Diagnostics</text>
      <text x="60" y="50" font-family="Arial, sans-serif" font-size="8" 
            text-anchor="middle" fill="#999">Intelligence Network</text>
      
      <!-- Decorative elements -->
      <circle cx="15" cy="15" r="3" fill="#00ff88" opacity="0.8"/>
      <circle cx="105" cy="15" r="3" fill="#0099ff" opacity="0.8"/>
      <circle cx="15" cy="45" r="2" fill="#00ff88" opacity="0.6"/>
      <circle cx="105" cy="45" r="2" fill="#0099ff" opacity="0.6"/>
      
      <!-- Connection lines -->
      <line x1="18" y1="15" x2="102" y2="15" stroke="#333" stroke-width="1" opacity="0.5"/>
      <line x1="17" y1="45" x2="103" y2="45" stroke="#333" stroke-width="1" opacity="0.5"/>
    </svg>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-favicon
  namespace: monitoring
data:
  # Simple favicon as SVG
  favicon.ico: |
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <rect width="32" height="32" fill="#1a1a1a"/>
      <text x="16" y="22" font-family="Arial" font-size="14" font-weight="bold" 
            text-anchor="middle" fill="#00ff88">O</text>
      <circle cx="8" cy="8" r="2" fill="#00ff88"/>
      <circle cx="24" cy="8" r="2" fill="#0099ff"/>
      <circle cx="8" cy="24" r="1" fill="#00ff88" opacity="0.7"/>
      <circle cx="24" cy="24" r="1" fill="#0099ff" opacity="0.7"/>
    </svg>