apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-email
  namespace: monitoring
data:
  # Grafana unified alerting configuration
  alerting.yaml: |
    # Contact points for email notifications
    contactPoints:
      - orgId: 1
        name: odin-email-alerts
        receivers:
          - uid: email-001
            type: email
            settings:
              addresses: admin@your-domain.com  # Change this to your email
              subject: "[ODIN] {{ .GroupLabels.alertname }} - {{ .Status }}"
              message: |
                Alert: {{ .GroupLabels.alertname }}
                Status: {{ .Status }}
                
                {{ range .Alerts }}
                Summary: {{ .Annotations.summary }}
                Description: {{ .Annotations.description }}
                Severity: {{ .Labels.severity }}
                Instance: {{ .Labels.instance }}
                Started: {{ .StartsAt }}
                {{ if .EndsAt }}Ended: {{ .EndsAt }}{{ end }}
                
                {{ end }}
                
                Dashboard: http://localhost:31494
                Prometheus: http://localhost:31493
            disableResolveMessage: false

    # Notification policies
    policies:
      - orgId: 1
        receiver: odin-email-alerts
        group_by:
          - alertname
          - grafana_folder
        group_wait: 15m  # Wait 15 minutes before first notification
        group_interval: 15m
        repeat_interval: 4h
        routes:
          - receiver: odin-email-alerts
            object_matchers:
              - ["severity", "=", "critical"]
            group_wait: 1m  # Critical alerts get faster notification
            repeat_interval: 1h
          - receiver: odin-email-alerts
            object_matchers:
              - ["alertname", "=~", ".*Power.*|.*Thermal.*|.*Temperature.*"]
            group_wait: 30s  # Thermal alerts get immediate notification
            repeat_interval: 2h

    # Mute timings (optional - for maintenance windows)
    muteTimes:
      - orgId: 1
        name: maintenance-window
        time_intervals:
          - times:
              - start_time: "02:00"
                end_time: "06:00"
            weekdays: ["sunday"]
---
# Updated Grafana deployment with SMTP configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.3.0
        ports:
        - containerPort: 3000
        env:
        # SMTP configuration
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: "smtp.gmail.com:587"  # Change to your SMTP server
        - name: GF_SMTP_USER
          value: "your-email@gmail.com"  # Change to your email
        - name: GF_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-smtp-secret
              key: smtp-password
        - name: GF_SMTP_FROM_ADDRESS
          value: "odin-monitoring@your-domain.com"  # Change to your email
        - name: GF_SMTP_FROM_NAME
          value: "ODIN Monitoring"
        - name: GF_SMTP_SKIP_VERIFY
          value: "false"
        # Unified alerting
        - name: GF_ALERTING_ENABLED
          value: "true"
        - name: GF_UNIFIED_ALERTING_ENABLED
          value: "true"
        - name: GF_ALERTING_EXECUTE_ALERTS
          value: "true"
        # Security and admin
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-alerting
          mountPath: /etc/grafana/provisioning/alerting
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboard-provider
      - name: grafana-alerting
        configMap:
          name: grafana-alerting-email