apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-scripts
  namespace: monitoring
data:
  check-process.sh: |
    #!/bin/sh
    # Check if process is running without pgrep
    ps aux | grep -v grep | grep -q "$1" && echo "Running" || echo "Not running"
  
  check-exporter.sh: |
    #!/bin/sh
    # Check if exporter is responding
    wget -q -O - http://localhost:${METRICS_PORT:-9100}/metrics > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "Exporter is healthy"
        exit 0
    else
        echo "Exporter is not responding"
        exit 1
    fi
  
  wait-for-startup.sh: |
    #!/bin/sh
    # Wait for process to start
    PROCESS=$1
    TIMEOUT=${2:-60}
    ELAPSED=0
    
    while [ $ELAPSED -lt $TIMEOUT ]; do
        if ps aux | grep -v grep | grep -q "$PROCESS"; then
            echo "Process $PROCESS started successfully"
            exit 0
        fi
        sleep 1
        ELAPSED=$((ELAPSED + 1))
    done
    
    echo "Timeout waiting for $PROCESS to start"
    exit 1