apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-2tb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-2tb
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-2tb
  local:
    path: /mnt/data/kubernetes/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rzrblade18-rz09-0623
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-2tb
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-2tb
  local:
    path: /mnt/data/kubernetes/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rzrblade18-rz09-0623
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-2tb
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-2tb
  local:
    path: /mnt/data/kubernetes/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rzrblade18-rz09-0623