apiVersion: batch/v1
kind: Job
metadata:
  name: monitoring-backup-manual
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: monitoring-backup-sa
      containers:
      - name: backup
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "/scripts/backup.sh"]
        volumeMounts:
        - name: backup-storage
          mountPath: /backups
        - name: prometheus-data
          mountPath: /prometheus-data
          readOnly: true
        - name: grafana-data
          mountPath: /grafana-data
          readOnly: true
        - name: scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: OnFailure
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: monitoring-backup-pvc
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: scripts
        configMap:
          name: backup-scripts
          defaultMode: 0755