apiVersion: v1
kind: ConfigMap
metadata:
  name: process-exporter-config
  namespace: monitoring
data:
  process-exporter.yaml: |
    # Monitor all processes
    process_names:
    - name: "{{.Comm}}"
      cmdline:
      - '.+'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: process-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: process-exporter
  template:
    metadata:
      labels:
        app: process-exporter
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: process-exporter
        image: ncabatoff/process-exporter:0.7.10
        args:
        - --config.path=/config/process-exporter.yaml
        - --web.listen-address=:9256
        ports:
        - containerPort: 9256
          hostPort: 9256
          name: metrics
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: config
          mountPath: /config
        env:
        - name: HOST_PROC
          value: /host/proc
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          privileged: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: config
        configMap:
          name: process-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: process-exporter
  namespace: monitoring
  labels:
    app: process-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9256
    targetPort: 9256
  selector:
    app: process-exporter