apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-update
  namespace: monitoring
data:
  add-tcp-rules.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: prometheus
      namespace: monitoring
    spec:
      template:
        spec:
          containers:
          - name: prometheus
            volumeMounts:
            - name: tcp-network-alerts
              mountPath: /etc/prometheus/rules/tcp
          volumes:
          - name: tcp-network-alerts
            configMap:
              name: tcp-network-alerts