apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki:3100/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      # ODIN monitoring namespace logs
      - job_name: odin-monitoring
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - monitoring
        pipeline_stages:
          - cri: {}
          - labeldrop:
              - filename
              - kubernetes_config_source
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__
      
      # System logs - simplified
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: system
              host: razerblade
              __path__: /var/log/syslog
        pipeline_stages:
          - multiline:
              firstline: '^\d{4}-\d{2}-\d{2}'
              max_wait_time: 3s
          - regex:
              expression: '^(?P<timestamp>\S+\s+\S+)\s+(?P<hostname>\S+)\s+(?P<program>\S+?)(\[(?P<pid>\d+)\])?\s*:\s*(?P<message>.*)$'
          - labels:
              program: